### ISSUE TITLE
如何構建exe檔案

### ISSUE THREAD

**Issue by carcaschoi** [BreakPointOo/AtmosphereUpdater#3]
新手+1，求教學🙇‍♂️🙇‍♂️

**Comment by BreakPointOo** [comment]
哈哈 我也是新手啦 你說的是Python文件編譯為exe嗎 如果是的話 pyinstaller -F app.py就可以了

**Comment by carcaschoi** [comment]
感謝，我試一試😀

**Comment by carcaschoi** [comment]
我好像失敗了，除了python，pip install pyinstaller還有什麼要下載🤔

**Comment by BreakPointOo** [comment]
应该不需要别的了 [http://c.biancheng.net/view/2690.html](http://c.biancheng.net/view/2690.html) 可以参考一下这个文档

**Comment by carcaschoi** [comment]
但是我構建完成後的dist/app.exe 一打開就會閃退

**Comment by carcaschoi** [comment]
不懂得如何加入ui

**Comment by carcaschoi** [comment]
![20210502_220231](https://user-images.githubusercontent.com/64573431/116815865-2472a480-ab92-11eb-8377-56c2dfc30ed6.jpg)

**Comment by carcaschoi** [comment]
成功了😄
